require("io.github.israiloff.config.lazy")
require("io.github.israiloff.config.keymap")
require("io.github.israiloff.config.formatting")
require("io.github.israiloff.config.editor")
require("io.github.israiloff.config.which-key")
